name: Frontend CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install & compile contracts at root
      run: |
        npm install
        npm run compile
    - name: npm install in app directory
      run: |
        cd app
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: Test
      run: |
        cd app
        npm test
      env:
        CI: true
    - name: lint
      run: |
        cd app
        npm run lint
