name: Frontend CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test frontend
      run: |
        npm install
        npm run compile
        cd app
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: lint
      run:
        npm run lint
